(function(){
const USERS='adab_bac_users_v2', LEGACY='adab_bac_user_v1', ADMIN='adab_bac_admin_v1', ACT='adab_bac_activity_v1', PUB='adab_bac_publication_v1';
const seed=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(USERS)||'[]')}catch(e){};if(!a.length){try{const old=JSON.parse(localStorage.getItem(LEGACY)||'null');if(old)a=[old]}catch(e){}}localStorage.setItem(USERS,JSON.stringify(a));return a};
const users=()=>{try{return JSON.parse(localStorage.getItem(USERS)||'[]')}catch(e){return []}};
const saveUsers=a=>localStorage.setItem(USERS,JSON.stringify(a));
const activity=()=>{try{return JSON.parse(localStorage.getItem(ACT)||'[]')}catch(e){return []}};
const log=x=>{const a=activity();a.unshift({at:new Date().toISOString(),text:x});localStorage.setItem(ACT,JSON.stringify(a.slice(0,80)))};
const pub=()=>{try{return JSON.parse(localStorage.getItem(PUB)||'{}')}catch(e){return {}}};
const savePub=x=>localStorage.setItem(PUB,JSON.stringify(x));
function login(u,p){if(u==='الأستاذ'&&p==='AdabBac@2026'){sessionStorage.setItem(ADMIN,'1');log('تسجيل دخول إداري');return true}return false}
function guard(){if(sessionStorage.getItem(ADMIN)!=='1'){location.href='admin-login.html';return false}return true}
function logout(){log('تسجيل خروج إداري');sessionStorage.removeItem(ADMIN);location.href='admin-login.html'}
window.AdabAdmin={login,guard,logout,users,saveUsers,log,activity,pub,savePub,seed};

document.addEventListener('DOMContentLoaded',()=>{
 if(!document.body.dataset.admin)return;
 if(!guard())return;seed();
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const views=$$('.view'), nav=$$('.nav button');
 function show(id){views.forEach(v=>v.classList.toggle('active',v.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===id));renderAll()}
 nav.forEach(n=>n.addEventListener('click',()=>show(n.dataset.view))); $('#logout').addEventListener('click',logout);
 function statusLabel(s){return {new:'مستخدم جديد',active:'مستخدم فعليّ',verified:'مستخدم موثّق',suspended:'معلّق'}[s]||'زائر'}
 function renderStats(){const u=users();$('#statUsers').textContent=u.length;$('#statActive').textContent=u.filter(x=>x.status==='active').length;$('#statVerified').textContent=u.filter(x=>x.status==='verified').length;$('#statContent').textContent=31;$('#recent').innerHTML=activity().slice(0,8).map(x=>`<div>${new Date(x.at).toLocaleString('ar-TN')} — ${x.text}</div>`).join('')||'<div class="empty">لا توجد عمليات بعد.</div>'}
 function renderUsers(){const q=($('#userSearch')?.value||'').trim();const filter=window._userFilter||'all';const all=users();['all','new','active','verified','suspended'].forEach(k=>{const el=document.getElementById('count'+({all:'All',new:'New',active:'Active',verified:'Verified',suspended:'Suspended'}[k]));if(el)el.textContent=k==='all'?all.length:all.filter(x=>x.status===k).length});const arr=all.filter(x=>(filter==='all'||x.status===filter)&&((x.name||'').includes(q)||(x.phone||'').includes(q)||(x.school||'').includes(q)));$('#usersBody').innerHTML=arr.map((x,i)=>`<tr><td>${x.name||'—'}</td><td>${x.school||'—'}</td><td>${x.phone||'—'}</td><td><span class="badge ${x.status}">${statusLabel(x.status)}</span></td><td><select class="select" data-user-status="${x.phone}" style="min-width:150px"><option value="new" ${x.status==='new'?'selected':''}>مستخدم جديد</option><option value="active" ${x.status==='active'?'selected':''}>مستخدم فعليّ · القائمة 1</option><option value="verified" ${x.status==='verified'?'selected':''}>مستخدم موثّق · القائمة 2</option><option value="suspended" ${x.status==='suspended'?'selected':''}>معلّق</option></select></td><td><button class="btn danger" data-delete="${x.phone}">حذف</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا يوجد مستخدمون.</td></tr>';
 $$('[data-user-status]').forEach(s=>s.addEventListener('change',()=>{const a=users(),u=a.find(x=>x.phone===s.dataset.userStatus);if(u){u.status=s.value;saveUsers(a);log(`تغيير حالة المستخدم ${u.name} إلى ${statusLabel(u.status)}`);renderAll()}}));
 $$('[data-delete]').forEach(b=>b.addEventListener('click',()=>{if(confirm('هل تريد حذف هذا الحساب؟')){const phone=b.dataset.delete,a=users().filter(x=>x.phone!==phone);saveUsers(a);log('حذف حساب مستخدم');renderAll()}}));}
 function renderContent(){const sections=[['الدروس',10],['التدريبات',10],['المرافقة',10],['البحوث',1]];const p=pub();$('#contentCards').innerHTML=sections.map(([n,c])=>`<div class="mini-card"><h3>${n}</h3><p>${c} موارد موجودة حاليًا.</p><label class="toggle-row"><span>إظهار هذا القسم للمستخدمين</span><span class="switch"><input type="checkbox" data-pub="${n}" ${p[n]!==false?'checked':''}><span class="slider"></span></span></label></div>`).join('');$$('[data-pub]').forEach(x=>x.addEventListener('change',()=>{const o=pub();o[x.dataset.pub]=x.checked;savePub(o);log(`${x.checked?'إظهار':'إخفاء'} قسم ${x.dataset.pub}`)}));}
 function renderSubmissions(){const el=document.getElementById('submissionBody');if(!el)return;const all=users();const mode=window._subFilter||'attempts';if(mode==='messages'){const rows=[];all.forEach(u=>(u.messages||[]).forEach(m=>rows.push({u,m})));el.innerHTML=rows.length?rows.reverse().map(({u,m})=>`<div class="submission-card"><div class="submission-head"><div><strong>${u.name||'تلميذ'}</strong><span>${new Date(m.date).toLocaleString('ar-TN')}</span></div><b class="attempt-status ${m.status||'pending'}">${m.status==='answered'?'تمت الإجابة':'رسالة واردة'}</b></div><p>${m.text||''}</p><div class="actions"><button class="btn" data-reply="${u.phone}" data-msg="${m.id||''}">الرد</button></div></div>`).join(''):'<div class="empty">لا توجد رسائل.</div>';el.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{const a=users(),u=a.find(x=>x.phone===b.dataset.reply);if(!u)return;const r=prompt('اكتب ردك إلى التلميذ:');if(r){u.messages=u.messages||[];u.messages.push({id:'reply_'+Date.now(),text:r,date:new Date().toISOString(),status:'answered',from:'teacher'});const target=u.messages.find(m=>m.id===b.dataset.msg);if(target)target.status='answered';saveUsers(a);log(`الرد على رسالة التلميذ ${u.name}`);renderSubmissions()}});return}const rows=[];all.forEach(u=>(u.attempts||[]).forEach(a=>rows.push({u,a})));el.innerHTML=rows.length?rows.reverse().map(({u,a})=>`<div class="submission-card"><div class="submission-head"><div><strong>${a.title||'عمل دون عنوان'}</strong><span>${u.name||'تلميذ'} · ${a.type||'عمل'} · ${new Date(a.date).toLocaleString('ar-TN')}</span></div><b class="attempt-status ${a.status||'sent'}">${a.status==='reviewed'?'تمت المراجعة':'بانتظار المراجعة'}</b></div><div class="submission-text">${(a.text||'').replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div><textarea class="teacher-note" data-note="${u.phone}" data-att="${a.id}" placeholder="ملاحظة الأستاذ...">${a.teacherNote||''}</textarea><div class="actions"><button class="btn" data-review="${u.phone}" data-att="${a.id}">حفظ المراجعة</button></div></div>`).join(''):'<div class="empty">لا توجد محاولات مرسلة.</div>';el.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const a=users(),u=a.find(x=>x.phone===b.dataset.review),att=u?.attempts?.find(x=>x.id===b.dataset.att);if(att){const note=el.querySelector(`[data-note="${b.dataset.review}"][data-att="${b.dataset.att}"]`);att.teacherNote=note?.value||'';att.status='reviewed';saveUsers(a);log(`مراجعة محاولة ${att.title} للتلميذ ${u.name}`);renderSubmissions()}})} function renderAll(){renderStats();renderUsers();renderContent();renderSubmissions();}
 $('#userSearch').addEventListener('input',renderUsers); window._userFilter='all'; document.querySelectorAll('.list-tab').forEach(b=>b.addEventListener('click',()=>{window._userFilter=b.dataset.filter;document.querySelectorAll('.list-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderUsers()})); $('#addUser').addEventListener('click',()=>$('#modal').classList.add('open')); $('#closeModal').addEventListener('click',()=>$('#modal').classList.remove('open'));
 $('#addForm').addEventListener('submit',e=>{e.preventDefault();const a=users();const u={name:$('#n').value.trim(),school:$('#s').value.trim(),phone:$('#ph').value.trim(),password:$('#pw').value,status:$('#st').value,progress:0,favorites:[],messages:[],createdAt:new Date().toISOString()};if(a.some(x=>x.phone===u.phone)){alert('يوجد حساب بهذا الرقم.');return}a.push(u);saveUsers(a);log(`إضافة مستخدم ${u.name}`);$('#modal').classList.remove('open');e.target.reset();renderAll()});
 $('#clearLog').addEventListener('click',()=>{if(confirm('مسح سجل النشاط؟')){localStorage.removeItem(ACT);renderAll()}});
 window._subFilter='attempts'; document.querySelectorAll('[data-subfilter]').forEach(b=>b.addEventListener('click',()=>{window._subFilter=b.dataset.subfilter;document.querySelectorAll('[data-subfilter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSubmissions()}));
 renderAll();
});
})();
